* Settings
  Really liking this way of organizing the config files.

  Kind of weird with having the defuns first, should look into that

  This config, ivymacs, takes very heavy inspiration from spacemacs and uses a combination of different packages to achieve that. Because we are using ordinary emacs, we have full controll over the .emacs.d folder which in the spacemacs cause we dont.

  The motivation for this project is twofold, one part is to try the ivy family of packages and the other to try using stock emacs where every package and keybinding is very clear. Sometimes spacemacs feels to big and cluttered.

* How to
  Add ":tangle no" to emacs-lisp begin src block to ignore that config

* Defuns

** open-config
   #+BEGIN_SRC emacs-lisp
   (defun open-config ()
     "Opens the init.el file"
     (interactive)
     (find-file "~/.emacs.d/settings.org"))
   #+END_SRC

** reload-config
   #+BEGIN_SRC emacs-lisp
   (defun reload-config ()
     (interactive)
     (with-temp-buffer
       (insert-file-contents "~/.emacs.d/init.el")
       (eval-buffer))
     (open-config))
   #+END_SRC


* Settings

** utf8
   #+BEGIN_SRC emacs-lisp
   (set-language-environment "utf-8")
   (setq locale-coding-system 'utf-8)
   (set-default-coding-systems 'utf-8)
   (set-terminal-coding-system 'utf-8)
   (set-keyboard-coding-system 'utf-8)
   (set-selection-coding-system 'utf-8)
   (setq buffer-file-coding-system 'utf-8-unix)
   (prefer-coding-system 'utf-8)

   (setenv "LANG" "en_US.UTF-8")
   #+END_SRC

** yes or no dialog
   #+BEGIN_SRC emacs-lisp
   (defadvice y-or-n-p (around prevent-dialog-yorn activate)
     "Prevent y-or-n-p from activating a dialog"
     (let ((use-dialog-box nil))
       ad-do-it))
   (fset 'yes-or-no-p 'y-or-n-p)
   #+END_SRC

** ignore bell
   #+BEGIN_SRC emacs-lisp
   (setq ring-bell-function 'ignore)
   #+END_SRC

** always display line and column numbers
   #+BEGIN_SRC emacs-lisp
   (setq line-number-mode t)
   (setq column-number-mode t)
   #+END_SRC

** lines should be 80 wide
   #+BEGIN_SRC emacs-lisp
   (setq fill-column 80)
   #+END_SRC

** never insert tabs
   #+BEGIN_SRC emacs-lisp
   (set-default 'indent-tabs-mode nil)
   #+END_SRC

** show empty lines
   #+BEGIN_SRC emacs-lisp
   (set-default 'indicate-empty-lines t)
   #+END_SRC

** no double space to end periods
   #+BEGIN_SRC emacs-lisp
   (set-default 'sentence-end-double-space nil)
   #+END_SRC

** Offer to create parent directories if they do not exist
   #+BEGIN_SRC emacs-lisp
   (defun my-create-non-existent-directory ()
     (let ((parent-directory (file-name-directory buffer-file-name)))
       (when (and (not (file-exists-p parent-directory))
                  (y-or-n-p (format "Directory `%s' does not exist! Create it?" parent-directory)))
         (make-directory parent-directory t))))

   (add-to-list 'find-file-not-found-functions 'my-create-non-existent-directory)
   #+END_SRC

** no startup message
   #+BEGIN_SRC emacs-lisp
   (setq inhibit-startup-message t)
   #+END_SRC

** backups and stuff
   #+BEGIN_SRC emacs-lisp
   (setq delete-old-versions -1 )		; delete excess backup versions silently
   (setq version-control t )		; use version control
   (setq vc-make-backup-files t )		; make backups file even when in version controlled dir
   (setq backup-directory-alist `(("." . "~/.backups")) ) ; which directory to put backups file
   (setq vc-follow-symlinks t )				       ; don't ask for confirmation when opening symlinked file
   (setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)) ) ;transform backups file name
   (setq delete-by-moving-to-trash t)
   #+END_SRC

** enable clipboard
   #+BEGIN_SRC emacs-lisp
   (setq x-select-enable-clipboard t)
   #+END_SRC

** apperences
   #+BEGIN_SRC emacs-lisp
   (when window-system
     (tooltip-mode -1)
     (tool-bar-mode -1)
     (menu-bar-mode -1)
     (scroll-bar-mode -1)
                                           ;(set-frame-font "Inconsolata 16")
     (blink-cursor-mode 1)
     (global-visual-line-mode)
     )
   #+END_SRC

** use another file instead of init.el for customizations
   #+BEGIN_SRC emacs-lisp
   (setq custom-file "~/.emacs.d/customized.el")
   (load custom-file)
   #+END_SRC
** enable recursive minibuffers
   When the minibuffer is active, we can still use call other commands for more minibuffers
   #+BEGIN_SRC emacs-lisp
   (setq enable-recursive-minibuffers t)
   #+END_SRC
** inidicate minibuffer depth
   ESC ESC ESC for closing anything you want
   #+BEGIN_SRC emacs-lisp
   (minibuffer-depth-indicate-mode 1)
   #+END_SRC

** performance
   Set the gc threshold to 10MiB
   #+BEGIN_SRC emacs-lisp
   (setq gc-cons-threshold (* 10 1024 1024))
   #+END_SRC

** more reasonable tab behaviour
   Default Tab is only indention. Now its first indentation then auto complete
   #+BEGIN_SRC emacs-lisp
                                           ;(setq tab-always-indent 'complete)
   #+END_SRC
   I think I want to try using some other binding for autocomplete

** frame title format
   Show the entire path of the file in the title
   #+BEGIN_SRC emacs-lisp
   (setq frame-title-format
         '((:eval (if (buffer-file-name)
                      (abbreviate-file-name (buffer-file-name))
                    "%b"))))
   #+END_SRC

** auto revert buffers when files have changed
   #+BEGIN_SRC emacs-lisp
   (global-auto-revert-mode t)
   #+END_SRC

** font
   #+BEGIN_SRC emacs-lisp
   ;;(set-face-attribute 'default t :font "SOURCE CODE PRO 16")
   #+END_SRC

   #+RESULTS:


* Org mode
** pretty source code blocks
   #+BEGIN_SRC emacs-lisp
   (setq org-edit-src-content-indentation 0
         org-src-tab-acts-natively t
         org-src-fontify-natively t
         org-confirm-babel-evaluate nil
         org-support-shift-select 'always)
   #+END_SRC

** org babel
   List of the languages for org babel
   #+BEGIN_SRC emacs-lisp
   (with-eval-after-load 'org
     (org-babel-do-load-languages
      'org-babel-load-languages
      '((emacs-lisp .t)
        (lisp . t))
      )
     )
   #+END_SRC

** Remove markup chars, /lol/ becomes italized "lol"
   #+BEGIN_SRC emacs-lisp
   (setq org-hide-emphasis-markers t)
   #+END_SRC

** set org directory
   #+BEGIN_SRC emacs-lisp
   (setq org-directory "~/Documents/notes"
         org-agenda-files '("~/Documents/notes"))
   #+END_SRC

** set notes file and templates
   #+BEGIN_SRC emacs-lisp
   (setq org-default-notes-file (concat org-directory "/notes.org")
         org-capture-templates
         '(("t" "Todo" entry (file+headline (concat org-directory "/gtd.org") "Tasks")
            "* TODO %?\n %i\n %a")
           ("d" "Literate" entry (file+headline (concat org-directory "/literate.org") "Literate")
            "* %?\n %i\n %a")
           ("n" "Note" entry (file+headline (concat org-directory "/notes.org") "Notes")
            "* %?")
           ("j" "Journal" entry (file+datetree (concat org-directory "/journal.org"))
            "* %?" :clock-in t :clock-resume t)
           ("l" "Read it later" checkitem (file+headline (concat org-directory "/readlater.org") "Read it later")
            "[ ] %?")))
   #+END_SRC


* Evil Mode
** evil
   #+BEGIN_SRC emacs-lisp
   (use-package evil :ensure t
     :init
     (setq evil-want-keybinding nil)  ; Required for evil-collection
     :config
     (evil-mode 1)
     ;; Set initial states for specific modes
     (evil-set-initial-state 'git-commit-mode 'insert))
   #+END_SRC

** evil-escape
   Quick escape from insert mode using key sequence
   #+BEGIN_SRC emacs-lisp
   (use-package evil-escape :ensure t
     :after evil
     :config
     (evil-escape-mode 1)
     (setq-default evil-escape-key-sequence "fj"))
   #+END_SRC

** evil-surround
   #+BEGIN_SRC emacs-lisp
   (use-package evil-surround :ensure t
     :after evil
     :config
     (global-evil-surround-mode 1))
   #+END_SRC

** evil-org
   Evil keybindings for org-mode
   #+BEGIN_SRC emacs-lisp
   (use-package evil-org :ensure t
     :after (evil org)
     :hook (org-mode . evil-org-mode)
     :config
     (require 'evil-org-agenda)
     (evil-org-agenda-set-keys))
   #+END_SRC


* Git / Magit
** magit
   #+BEGIN_SRC emacs-lisp
   (use-package magit :ensure t
     :commands magit-status)
   #+END_SRC
